# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0002_auto_20161116_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='from_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tree_menu.Menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='left_key',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='right_key',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
