# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_menu', '0006_auto_20161118_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='level',
            field=models.IntegerField(blank=True),
        ),
    ]
